(() => {
  const root = document.getElementById('pricing-catalog');
  if (!root) return;
  const groups = [['presence', 'Construire un parcours qui transforme l’intérêt en demande', ['M03', 'M04', 'M05', 'M06', 'M07']], ['visibilite', 'Gagner en visibilité locale sur Google', ['M08', 'M13']], ['automatisation', 'Réduire le délai entre une demande et votre réponse', ['M21', 'M22', 'M23']], ['diagnostic', 'Commencer par le bon problème', ['M01']]];
  const examples = {
    M03: 'Un indépendant qui reçoit surtout par téléphone : la page explique l’offre, rassure et mène vers un créneau ou WhatsApp.', M04: 'Une activité locale avec plusieurs services : chaque besoin a sa page et son appel à l’action, au lieu d’un menu qui disperse.', M05: 'Un commerce qui change régulièrement ses offres : les mises à jour restent simples sans refaire le site à chaque saison.', M06: 'Une boutique qui doit guider jusqu’au panier : fiches, réassurance et parcours d’achat restent cohérents sur mobile comme sur ordinateur.', M07: 'Une PME dont le site existe déjà : on garde ce qui aide, on retire ce qui ralentit la lecture et la demande.', M08: 'Un artisan recherché à Charleroi : fiche, pages locales et coordonnées cohérentes pour faciliter le choix sur Google.', M13: 'Une entreprise de service avec une zone précise : les pages répondent aux recherches réelles, sans produire du contenu pour remplir.', M21: 'Une demande de devis répétitive : le formulaire trie les informations utiles avant le premier échange.', M22: 'Un dirigeant qui relance ses prospects à la main : une séquence préparée garde le suivi régulier sans simuler une relation humaine.', M23: 'Une équipe qui recopie les mêmes données entre outils : les étapes sont reliées pour réduire les oublis et le temps perdu.', M01: 'Un projet encore flou : on identifie d’abord le blocage commercial ou opérationnel à résoudre avant de choisir un format.'
  };
  const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  fetch('/api/offers').then(r => r.ok ? r.json() : Promise.reject()).then(({ offers }) => {
    const byId = new Map(offers.map(o => [o.id, o]));
    root.innerHTML = groups.map(([id, title, ids]) => `<section class="pricing-group" id="${id}"><h3>${title}</h3><div class="pricing-list">${ids.map(key => { const offer = byId.get(key); return offer ? `<article class="price-card"><h4>${esc(offer.name)}</h4><strong>${esc(offer.price)}</strong><p>${esc(offer.description)}</p><div class="price-card__example"><b>Dans la pratique</b><span>${esc(examples[offer.id])}</span></div><a href="/contact.html?offer=${encodeURIComponent(offer.id)}">Préparer ma demande</a></article>` : ''; }).join('')}</div></section>`).join('');
  }).catch(() => { root.innerHTML = '<p>Les offres ne sont pas disponibles pour le moment. Écrivez-nous : nous vous expliquerons les options sans vous engager.</p>'; });
})();
